import { PoolClient } from 'pg';

/**
 * Migration: Create replay_cursors table
 *
 * Provides durable, DB-backed cursor state for IndexerService.replayEvents.
 *
 * Each replay run creates one row in this table when it starts.
 * After every committed batch, the row's `last_committed_offset` is updated
 * atomically inside the same batch transaction — meaning a process crash at
 * any point leaves the offset pointing at the last fully committed batch, and
 * a re-run can resume from exactly that position.
 *
 * Design notes:
 *  - `id` is a UUID generated by PostgreSQL (no application-side UUID dep).
 *  - `completed_at` is set to now() when all batches have been committed.
 *    The partial index WHERE completed_at IS NULL keeps the live-cursor lookup fast.
 *  - Only one active cursor per (contract_id, ledger) is enforced at the
 *    application layer (concurrent-replay lock), not at the DB level, so that
 *    historical completed rows are retained for auditing.
 */

export async function up(client: PoolClient): Promise<void> {
  console.log('Creating replay_cursors table...');

  await client.query(`
    CREATE TABLE IF NOT EXISTS replay_cursors (
      id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      contract_id            TEXT NOT NULL,
      ledger                 INTEGER NOT NULL,
      from_block             INTEGER,
      to_block               INTEGER,
      total_rows             INTEGER NOT NULL,
      last_committed_offset  INTEGER NOT NULL DEFAULT 0,
      started_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
      completed_at           TIMESTAMPTZ
    );
  `);

  // Partial index: speeds up the "find the active cursor for this contract+ledger"
  // lookup executed at the start of every replay.
  await client.query(`
    CREATE INDEX IF NOT EXISTS idx_replay_cursors_active
      ON replay_cursors (contract_id, ledger)
      WHERE completed_at IS NULL;
  `);

  console.log('replay_cursors table created successfully');
}

export async function down(client: PoolClient): Promise<void> {
  console.log('Dropping replay_cursors table...');

  await client.query(`DROP INDEX IF EXISTS idx_replay_cursors_active;`);
  await client.query(`DROP TABLE IF EXISTS replay_cursors;`);

  console.log('replay_cursors table dropped successfully');
}
